#!/bin/bash

## FLAC -> MP3 Conversion Script by thedash

# Possible usages:
# ./convert.sh file.flac
# ./convert.sh list.txt
# ./convert.sh /directory/to/convert/
# Files are created in the following format: "Artist - Year - Album - Track - Title.mp3"

# Note: this script assumes your files are already tagged correctly


## global variables
OUTPUT_FOLDER='/home/rgould/converted' # the folder where the converted files will be deposited
LAME_PARAMS='-V 0 --id3v2-only' # list of parameters for lame, excluding tagging variables


## check for required programs
if [[ -z $( which metaflac ) ]]; then
   echo "The program 'metaflac' is required to use this script."
   exit
elif [[ -z $( which flac ) ]]; then
   echo "The program 'flac' is required to use this script."
   exit
elif [[ -z $( which lame ) ]]; then
   echo "The program 'lame' is required to use this script."
   exit
fi

function checkflac {
   # check if file is a valid FLAC file
   [[ "$( file "$1" | grep ': FLAC audio' )" ]] && echo "$1" || echo ''
}
function convert {
   if [[ "$1" ]]; then
       # tags are grabbed before filename changes, so special characters are preserved
       fileinfo="$( metaflac --list "$1" )"
       taginfo="$( echo "$fileinfo" | grep -i 'comment\[[0-9]\{1,3\}\]' )"
       artist="$( echo "$taginfo" | grep -i ': Artist=' | cut -f2- -d'=' )"
       year="$( echo "$taginfo" | grep -i ': Date=' | cut -f2- -d'=' )"
       album="$( echo "$taginfo" | grep -i ': Album=' | cut -f2- -d'=' )"
       track="$( echo "$taginfo" | grep -i ': TrackNumber=' | cut -f2- -d'=' )"
       title="$( echo "$taginfo" | grep -i ': Title=' | cut -f2- -d'=' )"
       genre="$( echo "$taginfo" | grep -i ': Genre=' | cut -f2- -d'=' )"

       # change this $output_format variable if you want the tracks for be formatted differently
       output_directory_format="${OUTPUT_FOLDER}/$artist - $year - $album" 
       output_directory="$( echo "$output_directory_format" | sed 's/\:/-/g' | sed 's/?//g' )"
       mkdir -p "$output_directory"
       output_format="${OUTPUT_FOLDER}/$artist - $year - $album/$track - $title"
       #output_format="${OUTPUT_FOLDER}/$track - $title"
       output_file="$( echo "$output_format" | sed 's/\:/-/g' | sed 's/?//g' ).mp3" # couple of Windows/FAT/FAT32 disallowed characters
       flac -d "$1" -c | lame "$LAME_PARAMS" -S --tt "$title" --ta "$artist" --ty "$year" --tl "$album" --tn "$track" --tg "$genre" - "$output_file"
   fi
}

mkdir -p "$OUTPUT_FOLDER" 2> /dev/null

INPUT="$1" # catch the input parameter as a string
if [[ -f "$INPUT" ]]; then # input is an existing file
   if [[ "$( checkflac "$INPUT" )" ]]; then # input is a valid FLAC file
       convert "$INPUT"
   else # input is a list of FLAC files
       cat "$INPUT" | sort | while read item; do
        [[ "$( checkflac "$item" )" ]] && convert "$item"
       done
   fi
elif [[ -d "$INPUT" ]]; then # input is a directory/tree
   find "$INPUT" -type f | grep -i \.flac$ | sort | while read item; do # find every FLAC file in the tree
       [[ "$( checkflac "$item" )" ]] && convert "$item"
   done
else
   echo "'${INPUT}' is not a valid FLAC file, text file, or directory."
fi
